### ISSUE TITLE
Import Electron Category 

### ISSUE THREAD

**Issue by previsualconsent** [ECALELFS/ECALELF#113]
https://github.com/cms-egamma/cmssw/blob/master/EgammaAnalysis/ElectronTools/src/EnergyScaleCorrection_class.cc
https://github.com/cms-egamma/cmssw/blob/master/EgammaAnalysis/ElectronTools/interface/EnergyScaleCorrection_class.h#L177

**Comment by shervin86** [comment]
@previsualconsent can you confirm that it is fully integrated with #112 ?

**Comment by previsualconsent** [comment]
Fixed by #112
