### ISSUE TITLE
Pointer pointing in wrong place!

### ISSUE THREAD

**Issue by shervin86** [ECALELFS/ECALELF#116]
Big bug: _isMINIAOD is set to false after some events.
It's likely that a pointer is writing in the wrong memory location.

How to reproduce the issue:
cmsRun python/alcaSkimming.py type=MINIAODNTUPLE doTree=1 doExtraCalibTree=0 doExtraStudyTree=0 doEleIDTree=0 doTreeOnly=1  jsonFile= isCrab=1 skim= tagFile=config/reRecoTags/80X_mcRun2_asymptotic_2016_TrancheIV_v7.py isPrivate=0  bunchSpacing=0 files=/store/mc/RunIISummer16MiniAODv2/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/MINIAODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext1-v2/80000/F283191C-11C4-E611-973D-00215E2EB74E.root

**Comment by yhaddad** [comment]
@shervin86  This issue seems to disappear on `CMSSW_9_2_X`. I successfully ran the same command as you without noticing any bug (the log is here `/afs/cern.ch/user/y/yhaddad/public/forShervin/log.txt` )

**Comment by shervin86** [comment]
forgot to add that you need to add an assert to see if _isMINIAOD is always true
You won't see the bug otherwise

**Comment by previsualconsent** [comment]
I'm trying to test this as well but I get
python encountered the error: <type 'exceptions.ImportError'>
No module named hcalDDDSimConstants_cfi
I can't find this cfi anywhere.
