### ISSUE TITLE
Add EcalUncalibratedRecHit information to the ExtraCalibTree

### ISSUE THREAD

**Issue by ferriff** [ECALELFS/ECALELF#53]
* EcalUncalibratedRecHit information (mainly amplitude, jitter, OOT amplitudes) to the ExtraCalibTree
   * Also cleaned up the code to remove all copy-pasted sections in favour of functions.
   * Protections for missing collections are not implemented yet, but it seems they are not present either for the EcalRecHit case -> this can be done in the future for both cases.

From ferriff:urhChanges https://github.com/ferriff/ECALELF/tree/urhChanges
   * commit 4292250dfbc3de2c6c8a57791e2f7bf68c50b737 for testing
   * commit 955593a353cfb4aef0f5e7081af684acb7531671 cleaned up the code assuming a successful test

**Comment by shervin86** [comment]
Has been rebased and included in branch "rebase".
Status:
 - compiles
 - runs and produces two trees
The test are done assuming successful test, no test performed so far.
Commit Has been rebased and included in branch "rebase".
Status:
 - compiles
 - runs and produces two trees
The test are done assuming successful test, no test performed so far.
Commit 3e1cfc0423d354333679b7e805789df873bd0407 should be reverted to perform the check, but it cannot be reverted directly, it gives conflicts after the various other commits.

**Comment by shervin86** [comment]
done in 80X-devel branch
